// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace RussianElectionResultScraper.Web.Controllers {
    public partial class GraphController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected GraphController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.FileStreamResult PollingStationsByAttendance() {
            return new T4MVC_FileStreamResult(Area, Name, ActionNames.PollingStationsByAttendance);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.FileStreamResult VotersByAttendance() {
            return new T4MVC_FileStreamResult(Area, Name, ActionNames.VotersByAttendance);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.FileStreamResult PollingStationResults() {
            return new T4MVC_FileStreamResult(Area, Name, ActionNames.PollingStationResults);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.FileStreamResult CandidateResultsByAttendance() {
            return new T4MVC_FileStreamResult(Area, Name, ActionNames.CandidateResultsByAttendance);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public GraphController Actions { get { return MVC.Graph; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Graph";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string PollingStationsByAttendance = "PollingStationsByAttendance";
            public readonly string VotersByAttendance = "VotersByAttendance";
            public readonly string PollingStationResults = "PollingStationResults";
            public readonly string CandidateResultsByAttendance = "CandidateResultsByAttendance";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_GraphController: RussianElectionResultScraper.Web.Controllers.GraphController {
        public T4MVC_GraphController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.FileStreamResult PollingStationsByAttendance(string region, int? width, int? height, bool? showGrid) {
            var callInfo = new T4MVC_FileStreamResult(Area, Name, ActionNames.PollingStationsByAttendance);
            callInfo.RouteValueDictionary.Add("region", region);
            callInfo.RouteValueDictionary.Add("width", width);
            callInfo.RouteValueDictionary.Add("height", height);
            callInfo.RouteValueDictionary.Add("showGrid", showGrid);
            return callInfo;
        }

        public override System.Web.Mvc.FileStreamResult VotersByAttendance(string region, int? width, int? height, bool? showGrid) {
            var callInfo = new T4MVC_FileStreamResult(Area, Name, ActionNames.VotersByAttendance);
            callInfo.RouteValueDictionary.Add("region", region);
            callInfo.RouteValueDictionary.Add("width", width);
            callInfo.RouteValueDictionary.Add("height", height);
            callInfo.RouteValueDictionary.Add("showGrid", showGrid);
            return callInfo;
        }

        public override System.Web.Mvc.FileStreamResult PollingStationResults(string votingPlaceId, int? width, int? height, bool? showGrid) {
            var callInfo = new T4MVC_FileStreamResult(Area, Name, ActionNames.PollingStationResults);
            callInfo.RouteValueDictionary.Add("votingPlaceId", votingPlaceId);
            callInfo.RouteValueDictionary.Add("width", width);
            callInfo.RouteValueDictionary.Add("height", height);
            callInfo.RouteValueDictionary.Add("showGrid", showGrid);
            return callInfo;
        }

        public override System.Web.Mvc.FileStreamResult CandidateResultsByAttendance(string votingPlaceId, int? width, int? height, bool? showGrid) {
            var callInfo = new T4MVC_FileStreamResult(Area, Name, ActionNames.CandidateResultsByAttendance);
            callInfo.RouteValueDictionary.Add("votingPlaceId", votingPlaceId);
            callInfo.RouteValueDictionary.Add("width", width);
            callInfo.RouteValueDictionary.Add("height", height);
            callInfo.RouteValueDictionary.Add("showGrid", showGrid);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
